[auth]
#动态口令周期 (s) 600=10分钟
dynamic_period = 600
#时间漂移
dynamic_skew = 1

ip_whitelist = [
  "198.144.184.47",
  "108.174.48.108",
  "23.94.205.145",
  "108.174.48.102",
  "198.144.184.108",
  "198.144.184.57",
  "198.144.184.125",
]

#动态密钥
secret = "&&4sg123g[]/~"

# SMTP 发信白名单
email_whitelist = ["admin@example.com", "@example.com"]

email_regex = ["^test[0-9]+@example.com$"]
